### ISSUE TITLE
error converting

### ISSUE THREAD

**Issue by pikacom** [nlmaca/Wowza_Installers#3]
RHEL 9 throw error:

[root@xxxx,com lib]# java -jar wowza-letsencrypt-converter-0.2.jar -v /usr/local/WowzaStreamingEngine/conf/ /etc/letsencrypt/live/
Converting certificates: /etc/letsencrypt/live/ => /usr/local/WowzaStreamingEngine/conf/
Reading xxxxxxxx.com
Read error in xxxxxxxxx.com:java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: Invalid RSA private key
Error reading certificates, aborting without writing anything
[root@xxxxxx-com lib]#

**Comment by nlmaca** [comment]
@pikacom. I don't support or have tested with RHEL 9. 
Can you give more information about:
- Wowza version?
- Which java version are you using?
- How did you setup the SSL certificate on RHEL9?, because i have never tested with RHEL. The SSL setup is already 2 years old, so it wouldn't surprise me it has changed. 

i don't have any plans on updating the scripts (don't have the time for it at the moment).

Wowza have free streamlock certificates (they used to be paid years ago), so that might be a good alternative.

**Comment by pikacom** [comment]
Hi,
I manage to setup wowza 4.8.21+6 on RHEL 9 with 1.8.0.362 Java. 
The problem vas with certboot, I add directive --key-type rsa, and then converting is working.

**Comment by nlmaca** [comment]
Ok, glad you solved it. Be aware you need a higher Java version from 4.8.18+.
https://www.wowza.com/docs/wowza-streaming-engine-4-8-21-release-notes
